version: '3.8'
services:
  ffc-pay-settlement-to-return-file:
    build:
      context: .
      target: production
    image: ffc-pay-settlement-to-return-file
    container_name: ffc-pay-settlement-to-return-file
    volumes:
      - ./input:/home/node/input
      - ./output:/home/node/output
